#include "araneae/ast/Builder.h"
#include "araneae/error/ErrorCollector.h"

#include <assert.h>
#include <errno.h>
#include <stdio.h>
#include <string.h>

// Going to be generated by flex
extern void yyset_in(FILE *);

// Going to be generated by bison
extern void yyparse(void);

int yywrap() {
  printf("End of parsing file\n");
  return 1;
}

void yyerror(char *s) {
  errorCollectorAddError(ErrorStageParser, getTokenStartLine(),
                         getTokenStartColumn(), s);
}

void parseFile(const char *Path) {
  assert(ProgramRoot == NULL && "Some program already parsed");

  FILE *FD = fopen(Path, "r");
  if (!FD) {
    perror("Error while open the file");
    return;
  }

  yyset_in(FD);
  yyparse();
}
